# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: products.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'products.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproducts.proto\x12\x08products\"\'\n\x11GetProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\"H\n\x13ListProductsRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\"&\n\x15SearchProductsRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\x83\x01\n\x0fProductResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\r\n\x05stock\x18\x05 \x01(\x05\x12\x10\n\x08\x63\x61tegory\x18\x06 \x01(\t\x12\x11\n\timage_url\x18\x07 \x01(\t\"R\n\x14ListProductsResponse\x12+\n\x08products\x18\x01 \x03(\x0b\x32\x19.products.ProductResponse\x12\r\n\x05total\x18\x02 \x01(\x05\x32\xf8\x01\n\x0eProductService\x12\x44\n\nGetProduct\x12\x1b.products.GetProductRequest\x1a\x19.products.ProductResponse\x12M\n\x0cListProducts\x12\x1d.products.ListProductsRequest\x1a\x1e.products.ListProductsResponse\x12Q\n\x0eSearchProducts\x12\x1f.products.SearchProductsRequest\x1a\x1e.products.ListProductsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'products_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPRODUCTREQUEST']._serialized_start=28
  _globals['_GETPRODUCTREQUEST']._serialized_end=67
  _globals['_LISTPRODUCTSREQUEST']._serialized_start=69
  _globals['_LISTPRODUCTSREQUEST']._serialized_end=141
  _globals['_SEARCHPRODUCTSREQUEST']._serialized_start=143
  _globals['_SEARCHPRODUCTSREQUEST']._serialized_end=181
  _globals['_PRODUCTRESPONSE']._serialized_start=184
  _globals['_PRODUCTRESPONSE']._serialized_end=315
  _globals['_LISTPRODUCTSRESPONSE']._serialized_start=317
  _globals['_LISTPRODUCTSRESPONSE']._serialized_end=399
  _globals['_PRODUCTSERVICE']._serialized_start=402
  _globals['_PRODUCTSERVICE']._serialized_end=650
# @@protoc_insertion_point(module_scope)
